# Book settings
title: Coded Reality
author: Falaah Arif Khan and Abhishek Gupta
logo: maiei_logo.png

# Information about where the book exists on the web
repository:
  url                       : https://github.com/ai-ethics/coded-reality
  branch                    : master

launch_buttons:
  binderhub_url: https://mybinder.org

latex:
  latex_documents:
    targetname: book.tex
